name: CI Pipeline

on:
  push:
    branches:
      - master  # Запускаем при пушах в основную ветку
  pull_request:
    branches:
      - master  # Запускаем для pull-request в основную ветку

jobs:
  test:
    runs-on: ubuntu-latest  # Используем Ubuntu для выполнения тестов

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  

      - name: Install dependencies using uv
        run: |
          pip install uv --upgrade  # Устанавливаем uv
          uv --version  # Проверяем версию uv
          uv sync  # Синхронизируем зависимости, используя uv

      - name: Run migrations for dev environment
        run: |
          make migrate-dev  # Запуск миграций для dev базы данных

      - name: Run migrations for test environment
        run: |
          make migrate-test  # Запуск миграций для dev базы данных

      - name: Run tests
        run: |
          make test  # Запускаем тесты с помощью makefile
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Токен Codecov для приватных репозиториев
