version: "3.9"
services:
  postgres_dev:
    image: postgres:16
    container_name: pricely_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pricely_db
    ports:
      - "5432:5432" # Порт на хосте Linux: порт в контейнере
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data  # Исправлено на postgres_data_dev
    networks:
      - pricely_network

  postgres_test:
    image: postgres:16
    container_name: pricely_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pricely_test_db
    ports:
      - "5433:5432" # Тестовая БД на другом порту
    volumes:
      - postgres_data_test:/var/lib/postgresql/data  # Исправлено на postgres_data_test
    networks:
      - pricely_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # НОВЫЙ сервер для упражнений в SQL
  postgres_sql_practice:
    image: postgres:16
    container_name: pricely_postgres_sql_practice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sql_practice_db
    ports:
      - "5434:5432"  # Новый порт для практики
    volumes:
      - postgres_data_practice:/var/lib/postgresql/data
    networks:
      - pricely_network

volumes:
  postgres_data_dev:
  postgres_data_test:
  postgres_data_practice:  # Новый volume для практики

networks:
  pricely_network:
    driver: bridge
