"""ORM price_id added

Revision ID: 01b72cd0214b
Revises: 2dd026c24b80
Create Date: 2025-09-09 10:01:28.379927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b72cd0214b'
down_revision: Union[str, Sequence[str], None] = '2dd026c24b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_prices_product_id'), 'prices', ['product_id'], unique=False)
    op.add_column('products', sa.Column('price_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'products', 'prices', ['price_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'price_id')
    op.drop_index(op.f('ix_prices_product_id'), table_name='prices')
    # ### end Alembic commands ###
