"""upd

Revision ID: 10cea69b1587
Revises: 01b72cd0214b
Create Date: 2025-09-14 17:56:32.796676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10cea69b1587'
down_revision: Union[str, Sequence[str], None] = '01b72cd0214b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_products',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.add_column('prices', sa.Column('default_price', sa.Integer(), nullable=False))
    op.add_column('prices', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('prices', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('prices', 'default')
    op.drop_column('prices', 'claim')
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('products', 'categories',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint(op.f('products_price_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_user_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'price_id')
    op.drop_column('products', 'user_id')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.add_column('products', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('price_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_user_id_fkey'), 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('products_price_id_fkey'), 'products', 'prices', ['price_id'], ['id'])
    op.alter_column('products', 'categories',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('products', 'created_at')
    op.add_column('prices', sa.Column('claim', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('prices', sa.Column('default', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('prices', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('prices', 'created_at')
    op.drop_column('prices', 'default_price')
    op.drop_table('users_products')
    # ### end Alembic commands ###
