"""refactoring

Revision ID: 2dd026c24b80
Revises: da72caba4ed9
Create Date: 2025-09-08 15:38:48.868663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd026c24b80'
down_revision: Union[str, Sequence[str], None] = 'da72caba4ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'previous_with_card',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prices', 'previous_without_card',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('prices_product_id_fkey'), 'prices', type_='foreignkey')
    op.create_foreign_key(None, 'prices', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('products_user_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('fk_products_price_id'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'price_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_products_price_id'), 'products', 'prices', ['price_id'], ['id'])
    op.create_foreign_key(op.f('products_user_id_fkey'), 'products', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.create_foreign_key(op.f('prices_product_id_fkey'), 'prices', 'products', ['product_id'], ['id'])
    op.alter_column('prices', 'previous_without_card',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prices', 'previous_with_card',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
