"""Named Article instead of Articule in the Product Table

Revision ID: 524113e4aeb3
Revises: aa97b3c1883a
Create Date: 2026-02-03 20:31:26.325343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '524113e4aeb3'
down_revision: Union[str, Sequence[str], None] = 'aa97b3c1883a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products', sa.Column('article', sa.String(length=10), nullable=False)
    )
    op.drop_column('products', 'articule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column(
            'articule', sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    op.drop_column('products', 'article')
    # ### end Alembic commands ###
