"""Уделение столбцов Категории, Ссылка на изображение, Рейтинг

Revision ID: 5c523bf3951d
Revises: 7fb41109dc4a
Create Date: 2025-11-07 09:12:51.191206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c523bf3951d'
down_revision: Union[str, Sequence[str], None] = '7fb41109dc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
