"""Deleted field - DEFAULT PRICE in prices

Revision ID: 7fb41109dc4a
Revises: 1a85fac1d2c0
Create Date: 2025-09-27 13:19:55.838524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb41109dc4a'
down_revision: Union[str, Sequence[str], None] = '1a85fac1d2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'default_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('default_price', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
