name: CI Pipeline

on:
  push:
    branches:
      - master  # Запускаем при пушах в основную ветку
  pull_request:
    branches:
      - master  # Запускаем для pull-request в основную ветку

jobs:
  test:
    runs-on: ubuntu-latest  # Используем Ubuntu для выполнения тестов

    services:
      postgres_dev:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: pricely_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      postgres_test:
        image: postgres:16
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: pricely_test_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  

      - name: Install dependencies using uv
        run: |
          pip install uv --upgrade  # Устанавливаем uv
          uv --version  # Проверяем версию uv
          uv sync  # Синхронизируем зависимости, используя uv

      - name: Wait for PostgreSQL to be ready (dev)
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres_dev to be ready..."
            sleep 2
          done

      - name: Wait for PostgreSQL to be ready (test)
        run: |
          until pg_isready -h localhost -p 5433 -U postgres; do
            echo "Waiting for postgres_test to be ready..."
            sleep 2
          done

      - name: Run migrations for dev environment
        run: |
          make migrate-dev  # Запуск миграций для dev базы данных

      - name: Run migrations for test environment
        run: |
          make migrate-test  # Запуск миграций для dev базы данных

      - name: Run tests
        run: |
          make test  # Запускаем тесты с помощью makefile
        
